### PR TITLE
seed_instance hotfix

### PR DESCRIPTION
**Pull request by serranoarevalo**
Solves #65

### CODE REVIEW

**Comment by serranoarevalo** [comment]
Hoping to get this one merged soon, currently django-seed is broken.

**Comment by hgarcia101685** [comment]
Any word on when this might be merged?  
I suppose we could pull the hotfix branch and build off of that branch in the interim?

**Comment by zodman** [comment]
not no body will merge ?

**Comment by ezzy1337** [comment]
You can add `Faker==2.0.5` in your project's requirements.txt to force the Faker version before the deprecation error was added. This should still get merged, but until then it's not a terrible workaround.

This only works because django-seed doesn't specify a version for Faker, so your projects required version will take precedence.

Here is the Faker commit where the Deprecation warning was added. https://github.com/joke2k/faker/commit/5257c8f2ecb607ce02b61b061dcb5e1cebc3d716#diff-7305ecb8d2913b8789f3cb6a9a307c7a

**Comment by zodman** [comment]
somone merge!

**Comment by shonjiho** [comment]
Please Merge. My Django-Seed Broken.

**Pull request merged**
